### PR TITLE
Resolves #58 by adding a basic devcontainer.json to the project.

### LINKED ISSUE #58: Add support for DevContainers

### PR DESCRIPTION
**Pull request by ParadoxicalSerenity**
I hope this helps, it's nothing special but seems to work well as a good starting point.

### CODE REVIEW

**Review by kirkone — APPROVED** [review]

**Comment by kirkone** [comment]
Thank you very much!

**Comment by kirkone** [comment]
@ParadoxicalSerenity sorry, the pipeline seems to be broken. Will fix this tomorrow.

**Comment by tmueller** [comment]
@kirkone currently is not available and I am afraid I can't help here. But please have a little more patience, @kirkone  will be back real soon and I am sure he will have a look then.

**Comment by tmueller** [comment]
No worries, it didn't come across as if you were rushing anything. 

This being an open source project, the maintainers sometimes need a reminder. So your inquiry is perfectly valid 👍 

@kirkone will have a look real soon.

**Comment by kirkone** [comment]
https://stackoverflow.com/questions/76952023/how-to-make-github-actions-safely-access-secrets-for-prs-created-from-forks

This might be the problem here.

**Comment by kirkone** [comment]
@ParadoxicalSerenity thanks again for your contribution! 🥳

I did force the merge as you suggested and will have a look into how we could solve the deployment issue later.
We will find a solution that will allow to deploy the active PR without having the risk of deploying something that we do not want.

**Comment by kirkone** [comment]
@ParadoxicalSerenity may I ask how you found this project and what is your opinion on it so far?

**Pull request merged**
